language: node_js
node_js:
  - "9.8"
install:
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  bucket: scottskender.com
  local-dir: public
  acl: public_read
  on:
    repo: vandosant/scottskender-v2
  skip_cleanup: true
